apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vdpb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vdpb
    app.kubernetes.io/part-of: ci10t-777-0090-app
  name: devfile-sample-vdpb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vdpb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vdpb
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0090-tenant/ci10t-777-0090-app/devfile-sample-vdpb@sha256:39153965d4a08eca08bf84ef76efc07ac40dd5ee56868ec12f2e673b0142fba1
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
